// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbcOY-ia11Zxfw_Vsr9yu_BeMyKMgEP8U',
    appId: '1:388823757393:web:ccc3fd6fe0e0dbb985fe70',
    messagingSenderId: '388823757393',
    projectId: 'taskmanager-52bed',
    authDomain: 'taskmanager-52bed.firebaseapp.com',
    databaseURL: 'https://taskmanager-52bed-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taskmanager-52bed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Utt_ssfXTUhPDFpM7kuMg35PzLG_C9w',
    appId: '1:388823757393:android:7ddaeeba5b6831e585fe70',
    messagingSenderId: '388823757393',
    projectId: 'taskmanager-52bed',
    databaseURL: 'https://taskmanager-52bed-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taskmanager-52bed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_szgAggKhOmfk2cEDU0r8op68Yx0Acx8',
    appId: '1:388823757393:ios:4ff45f2f2dd7ac9285fe70',
    messagingSenderId: '388823757393',
    projectId: 'taskmanager-52bed',
    databaseURL: 'https://taskmanager-52bed-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taskmanager-52bed.firebasestorage.app',
    iosBundleId: 'com.example.tasksManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_szgAggKhOmfk2cEDU0r8op68Yx0Acx8',
    appId: '1:388823757393:ios:4ff45f2f2dd7ac9285fe70',
    messagingSenderId: '388823757393',
    projectId: 'taskmanager-52bed',
    databaseURL: 'https://taskmanager-52bed-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taskmanager-52bed.firebasestorage.app',
    iosBundleId: 'com.example.tasksManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbcOY-ia11Zxfw_Vsr9yu_BeMyKMgEP8U',
    appId: '1:388823757393:web:82448f6d51399c3d85fe70',
    messagingSenderId: '388823757393',
    projectId: 'taskmanager-52bed',
    authDomain: 'taskmanager-52bed.firebaseapp.com',
    databaseURL: 'https://taskmanager-52bed-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taskmanager-52bed.firebasestorage.app',
  );
}
